name: Test and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Set up Node.js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      # Install dependencies
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
      
      # Run tests and generate coverage
      - name: Run tests and generate coverage
        working-directory: frontend
        run: npm run test:coverage
      
      # Check coverage thresholds
      - name: Check coverage thresholds
        working-directory: frontend
        run: npm run coverage:check
      
      # Upload coverage reports
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
      
      # Archive coverage reports
      - name: Archive coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: frontend/coverage
          if-no-files-found: warn
